# Generated by Django 3.0.8 on 2020-07-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery/%Y/%m/%d/')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
