# Generated by Django 3.0.8 on 2020-07-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
