# Generated by Django 3.0.8 on 2020-07-11 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='SpecialOffer',
        ),
    ]
