# Generated by Django 3.0.8 on 2020-07-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0002_auto_20200711_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialOffer',
            new_name='Special',
        ),
    ]
