# Generated by Django 3.0.8 on 2020-07-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone',
        ),
        migrations.AddField(
            model_name='contacts',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
