# Generated by Django 3.0.8 on 2020-07-13 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='show',
            new_name='is_published',
        ),
    ]
