# Generated by Django 3.0.8 on 2020-07-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20200713_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='is_published',
            new_name='show',
        ),
    ]
